services:
  # 資料庫
  db:
    image: mariadb:10.5
    container_name: zabbix-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=tyJy8b7BJJDQ
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
    volumes:
      - zbx_db_data:/var/lib/mysql
    networks:
      - zbx-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    container_name: zabbix-server
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
    volumes:
      - zbx_server_data:/var/lib/zabbix
    networks:
      - zbx-net

  # Zabbix Web
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.2-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - db
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
      - ZBX_SERVER_HOST=172.16.10.236
      - PHP_TZ=Asia/Taipei
    volumes:
      - zbx_web_data:/var/lib/zabbix
    networks:
      - zbx-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zabbix-agent
    # 使用 host network & host PID namespace
    network_mode: host
    pid: "host"
    restart: unless-stopped
    # 解除 AppArmor 限制
    security_opt:
      - apparmor:unconfined
    environment:
      # 必須跟 UI 裡 Hosts → Zabbix server 的 Name 一樣
      ZBX_HOSTNAME: "Zabbix server"
      # 被動檢查來源 (Server→Agent)
      ZBX_SERVER_HOST: "172.16.10.236,172.18.0.3"
      ZBX_SERVER_PORT: "10051"
      # 主動檢查 (Agent→Server)
      ZBX_SERVER_ACTIVE: "172.16.10.236"
      # Agent 監聽埠（預設 10050）
      ZBX_LISTEN_PORT: "10050"
    # 不要再去掛載 /proc,/sys 以免覆寫系統
    # 如果需要讀 host fs，可改為掛到 /host 之類的非預設路徑
    #volumes:
    #  - /proc:/host/proc:ro
    #  - /sys:/host/sys:ro
    #  - /:/host/rootfs:ro


volumes:
  zbx_db_data:
  zbx_server_data:
  zbx_web_data:

networks:
  zbx-net:
    driver: bridge
