services:
  db:
    image: mariadb:11.5.2
    container_name: zabbix-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=tyJy8b7BJJDQ
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-ptyJy8b7BJJDQ", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - zbx_db_data:/var/lib/mysql
    networks:
      - zbx-net

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    container_name: zabbix-server
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
    volumes:
      - zbx_server_data:/var/lib/zabbix
    networks:
      - zbx-net

  # Zabbix Web
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.2-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - db
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
      - ZBX_SERVER_HOST=172.16.10.236
      - PHP_TZ=Asia/Taipei
    volumes:
      - zbx_web_data:/var/lib/zabbix
    networks:
      - zbx-net

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zabbix-agent
    network_mode: host
    pid: "host"
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "172.16.10.236,172.18.0.3"
      ZBX_SERVER_PORT: "10051"
      ZBX_SERVER_ACTIVE: "172.16.10.236"
      ZBX_LISTEN_PORT: "10050"

volumes:
  zbx_db_data:
  zbx_server_data:
  zbx_web_data:

networks:
  zbx-net:
    driver: bridge
