services:
  db:
    image: mariadb:10.5
    container_name: zabbix-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=tyJy8b7BJJDQ
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
    volumes:
      - zbx_db_data:/var/lib/mysql
    networks:
      - zbx-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.2-latest
    container_name: zabbix-server
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
    volumes:
      - zbx_server_data:/var/lib/zabbix
    networks:
      - zbx-net

  # Zabbix Web (PHP + Apache)
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.2-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - db
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=k9jloXAuUdQC
      # 這裡把 ZBX_SERVER_HOST 改成指向 zabbix-server 容器名稱（內部網路可互相解析）
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Taipei
    volumes:
      - zbx_web_data:/var/lib/zabbix
    networks:
      - zbx-net

  # Zabbix Agent
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.2-latest
    container_name: zabbix-agent
    network_mode: host   # Zabbix Agent 使用 Host Network
    pid: "host"
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "192.168.10.128,172.18.0.3"
      ZBX_SERVER_PORT: "10051"
      ZBX_SERVER_ACTIVE: "192.168.10.128"
      ZBX_LISTEN_PORT: "10050"
    # Zabbix Agent 使用 host network，不需加入 zbx-net

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - zabbix-server
      - zabbix-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Grafana 預設管理員帳號密碼可自行調整
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # 自動安裝 Zabbix 外掛：
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      # 指定時區
      - GF_DEFAULT_LOCALE=zh-tw
      - GF_SERVER_ROOT_URL=http://localhost:3000
    volumes:
      - zbx_grafana_data:/var/lib/grafana
    networks:
      - zbx-net

volumes:
  zbx_db_data:
  zbx_server_data:
  zbx_web_data:
  zbx_grafana_data:

networks:
  zbx-net:
    driver: bridge

